### ISSUE TITLE
Use of undeclared type or module `linkme`

### ISSUE THREAD

**Issue by Dominilk** [CodeChain-io/intertrait#3]
Hello! When trying to run the example provided on your crates.io page https://crates.io/crates/intertrait, I'm getting the following error:

```
error[E0433]: failed to resolve: use of undeclared type or module `linkme`
  --> src/main.rs:12:1
   |
12 | #[cast_to]
   | ^^^^^^^^^^ use of undeclared type or module `linkme`
```

This is my first issue so sorry if I forgot any important details.

Best regards,
Dominik

**Comment by majecty** [comment]
Currently, you need to add "linkme" in your Cargo dependencies to use "intertrait".
I don't know that is a mistake or an intention.

**Comment by dynaxis** [comment]
I'll look into this issue. I think it should be thought as a bug, though adding `linkme` in your dependencies should remedy the problem.

Thanks for reporting the problem.

**Comment by dynaxis** [comment]
I investigated more on this issue, and unfortunately there is no way to resolve this issue without adding `linkme` to your crate as a direct dependency. I can update `intertrait` to reexport `linkme` symbols inserted by the `intertrait` macros and use the reexports to avoid the hassles of adding `linkme` as a direct dependency. But `linkme` macro emits code snippets referencing itself as `::linkme::...`, and the problem still manifests as the result.

So please add a direct dependency on `linkme` in your crate. I'll document it clearly and will tighten paths emitted by the `intertrait` macro for possible problems.

**Comment by dynaxis** [comment]
Closing this issue.
* Document was added to `README.md` to clarify the dependency requirement.
* Macro outputs were improved not to cause problems in different contexts (though no problem has been reported for the previous outputs)

**Comment by dynaxis** [comment]
FYI, a new release `0.2.1` is out with the above-mentioned commits together with all the pending commits since the last release.
